version: '3.3'

services:
  nginx:
    build: 
    context: .
    dockerfile: Dockerfile
    args:
      PATH_TO_WORLD_DATA: ${PATH_TO_WORLD_SAVE}
    ports:
      - "${NGINX_EXPOSED_PORT}:80"
  minecraft:
    image: itzg/minecraft-server
    depends_on:
      - nginx
    ports:
     - "6969:25565"
    environment:
      EULA: "TRUE"
      WORLD: "localhost:${NGINX_EXPOSED_PORT}"
